/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as rootRouteImport } from './routes/(root)/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as rootSettingsImport } from './routes/(root)/settings'
import { Route as rootProfileImport } from './routes/(root)/profile'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authSigninImport } from './routes/(auth)/signin'

// Create/Update Routes

const rootRouteRoute = rootRouteImport.update({
  id: '/(root)',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const rootSettingsRoute = rootSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteRoute,
} as any)

const rootProfileRoute = rootProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteRoute,
} as any)

const authSignupRoute = authSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)

const authSigninRoute = authSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/(root)': {
      id: '/(root)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof authRouteImport
    }
    '/(root)/profile': {
      id: '/(root)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof rootProfileImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/settings': {
      id: '/(root)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof rootSettingsImport
      parentRoute: typeof rootRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface rootRouteRouteChildren {
  rootProfileRoute: typeof rootProfileRoute
  rootSettingsRoute: typeof rootSettingsRoute
}

const rootRouteRouteChildren: rootRouteRouteChildren = {
  rootProfileRoute: rootProfileRoute,
  rootSettingsRoute: rootSettingsRoute,
}

const rootRouteRouteWithChildren = rootRouteRoute._addFileChildren(
  rootRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof rootRouteRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof rootProfileRoute
  '/settings': typeof rootSettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof rootRouteRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof rootProfileRoute
  '/settings': typeof rootSettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(root)': typeof rootRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(root)/profile': typeof rootProfileRoute
  '/(root)/settings': typeof rootSettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/signup' | '/profile' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/profile' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(root)'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(root)/profile'
    | '/(root)/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  rootRouteRoute: typeof rootRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  rootRouteRoute: rootRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/(root)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/signin",
        "/(auth)/signup"
      ]
    },
    "/(root)": {
      "filePath": "(root)/route.tsx",
      "children": [
        "/(root)/profile",
        "/(root)/settings"
      ]
    },
    "/(auth)/signin": {
      "filePath": "(auth)/signin.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.tsx",
      "parent": "/(auth)"
    },
    "/(root)/profile": {
      "filePath": "(root)/profile.tsx",
      "parent": "/(root)"
    },
    "/(root)/settings": {
      "filePath": "(root)/settings.tsx",
      "parent": "/(root)"
    }
  }
}
ROUTE_MANIFEST_END */
